funcroi-config -roi BaleenHP.lh.fir.012.roicfg -label aparc2009-lh-012.label -analysis ya.BaleenHP.fir.sm8.lh 
funcroi-config -roi BaleenHP.lh.fir.025.roicfg -label aparc2009-lh-025.label -analysis ya.BaleenHP.fir.sm8.lh 
funcroi-config -roi BaleenHP.lh.fir.034.roicfg -label aparc2009-lh-034.label -analysis ya.BaleenHP.fir.sm8.lh 
funcroi-config -roi BaleenHP.lh.fir.037.roicfg -label aparc2009-lh-037.label -analysis ya.BaleenHP.fir.sm8.lh 
funcroi-config -roi BaleenHP.lh.fir.038.roicfg -label aparc2009-lh-038.label -analysis ya.BaleenHP.fir.sm8.lh 
funcroi-config -roi BaleenHP.lh.fir.044.roicfg -label aparc2009-lh-044.label -analysis ya.BaleenHP.fir.sm8.lh 
funcroi-config -roi BaleenHP.lh.fir.073.roicfg -label aparc2009-lh-073.label -analysis ya.BaleenHP.fir.sm8.lh 
funcroi-config -roi BaleenHP.lh.fir.074.roicfg -label aparc2009-lh-074.label -analysis ya.BaleenHP.fir.sm8.lh 
funcroi-config -roi BaleenHP.lh.spm.012.roicfg -label aparc2009-lh-012.label -analysis ya.BaleenHP.spm.sm8.lh 
funcroi-config -roi BaleenHP.lh.spm.025.roicfg -label aparc2009-lh-025.label -analysis ya.BaleenHP.spm.sm8.lh 
funcroi-config -roi BaleenHP.lh.spm.034.roicfg -label aparc2009-lh-034.label -analysis ya.BaleenHP.spm.sm8.lh 
funcroi-config -roi BaleenHP.lh.spm.037.roicfg -label aparc2009-lh-037.label -analysis ya.BaleenHP.spm.sm8.lh 
funcroi-config -roi BaleenHP.lh.spm.038.roicfg -label aparc2009-lh-038.label -analysis ya.BaleenHP.spm.sm8.lh 
funcroi-config -roi BaleenHP.lh.spm.044.roicfg -label aparc2009-lh-044.label -analysis ya.BaleenHP.spm.sm8.lh 
funcroi-config -roi BaleenHP.lh.spm.073.roicfg -label aparc2009-lh-073.label -analysis ya.BaleenHP.spm.sm8.lh 
funcroi-config -roi BaleenHP.lh.spm.074.roicfg -label aparc2009-lh-074.label -analysis ya.BaleenHP.spm.sm8.lh 
funcroi-config -roi BaleenHP.rh.fir.012.roicfg -label aparc2009-rh-012.label -analysis ya.BaleenHP.fir.sm8.rh 
funcroi-config -roi BaleenHP.rh.fir.025.roicfg -label aparc2009-rh-025.label -analysis ya.BaleenHP.fir.sm8.rh 
funcroi-config -roi BaleenHP.rh.fir.034.roicfg -label aparc2009-rh-034.label -analysis ya.BaleenHP.fir.sm8.rh 
funcroi-config -roi BaleenHP.rh.fir.037.roicfg -label aparc2009-rh-037.label -analysis ya.BaleenHP.fir.sm8.rh 
funcroi-config -roi BaleenHP.rh.fir.038.roicfg -label aparc2009-rh-038.label -analysis ya.BaleenHP.fir.sm8.rh 
funcroi-config -roi BaleenHP.rh.fir.044.roicfg -label aparc2009-rh-044.label -analysis ya.BaleenHP.fir.sm8.rh 
funcroi-config -roi BaleenHP.rh.fir.073.roicfg -label aparc2009-rh-073.label -analysis ya.BaleenHP.fir.sm8.rh 
funcroi-config -roi BaleenHP.rh.fir.074.roicfg -label aparc2009-rh-074.label -analysis ya.BaleenHP.fir.sm8.rh 
funcroi-config -roi BaleenHP.rh.spm.012.roicfg -label aparc2009-rh-012.label -analysis ya.BaleenHP.spm.sm8.rh 
funcroi-config -roi BaleenHP.rh.spm.025.roicfg -label aparc2009-rh-025.label -analysis ya.BaleenHP.spm.sm8.rh 
funcroi-config -roi BaleenHP.rh.spm.034.roicfg -label aparc2009-rh-034.label -analysis ya.BaleenHP.spm.sm8.rh 
funcroi-config -roi BaleenHP.rh.spm.037.roicfg -label aparc2009-rh-037.label -analysis ya.BaleenHP.spm.sm8.rh 
funcroi-config -roi BaleenHP.rh.spm.038.roicfg -label aparc2009-rh-038.label -analysis ya.BaleenHP.spm.sm8.rh 
funcroi-config -roi BaleenHP.rh.spm.044.roicfg -label aparc2009-rh-044.label -analysis ya.BaleenHP.spm.sm8.rh 
funcroi-config -roi BaleenHP.rh.spm.073.roicfg -label aparc2009-rh-073.label -analysis ya.BaleenHP.spm.sm8.rh 
funcroi-config -roi BaleenHP.rh.spm.074.roicfg -label aparc2009-rh-074.label -analysis ya.BaleenHP.spm.sm8.rh 
funcroi-config -roi BaleenLP.lh.fir.012.roicfg -label aparc2009-lh-012.label -analysis ya.BaleenLP.fir.sm8.lh 
funcroi-config -roi BaleenLP.lh.fir.025.roicfg -label aparc2009-lh-025.label -analysis ya.BaleenLP.fir.sm8.lh 
funcroi-config -roi BaleenLP.lh.fir.034.roicfg -label aparc2009-lh-034.label -analysis ya.BaleenLP.fir.sm8.lh 
funcroi-config -roi BaleenLP.lh.fir.037.roicfg -label aparc2009-lh-037.label -analysis ya.BaleenLP.fir.sm8.lh 
funcroi-config -roi BaleenLP.lh.fir.038.roicfg -label aparc2009-lh-038.label -analysis ya.BaleenLP.fir.sm8.lh 
funcroi-config -roi BaleenLP.lh.fir.044.roicfg -label aparc2009-lh-044.label -analysis ya.BaleenLP.fir.sm8.lh 
funcroi-config -roi BaleenLP.lh.fir.073.roicfg -label aparc2009-lh-073.label -analysis ya.BaleenLP.fir.sm8.lh 
funcroi-config -roi BaleenLP.lh.fir.074.roicfg -label aparc2009-lh-074.label -analysis ya.BaleenLP.fir.sm8.lh 
funcroi-config -roi BaleenLP.lh.spm.012.roicfg -label aparc2009-lh-012.label -analysis ya.BaleenLP.spm.sm8.lh 
funcroi-config -roi BaleenLP.lh.spm.025.roicfg -label aparc2009-lh-025.label -analysis ya.BaleenLP.spm.sm8.lh 
funcroi-config -roi BaleenLP.lh.spm.034.roicfg -label aparc2009-lh-034.label -analysis ya.BaleenLP.spm.sm8.lh 
funcroi-config -roi BaleenLP.lh.spm.037.roicfg -label aparc2009-lh-037.label -analysis ya.BaleenLP.spm.sm8.lh 
funcroi-config -roi BaleenLP.lh.spm.038.roicfg -label aparc2009-lh-038.label -analysis ya.BaleenLP.spm.sm8.lh 
funcroi-config -roi BaleenLP.lh.spm.044.roicfg -label aparc2009-lh-044.label -analysis ya.BaleenLP.spm.sm8.lh 
funcroi-config -roi BaleenLP.lh.spm.073.roicfg -label aparc2009-lh-073.label -analysis ya.BaleenLP.spm.sm8.lh 
funcroi-config -roi BaleenLP.lh.spm.074.roicfg -label aparc2009-lh-074.label -analysis ya.BaleenLP.spm.sm8.lh 
funcroi-config -roi BaleenLP.rh.fir.012.roicfg -label aparc2009-rh-012.label -analysis ya.BaleenLP.fir.sm8.rh 
funcroi-config -roi BaleenLP.rh.fir.025.roicfg -label aparc2009-rh-025.label -analysis ya.BaleenLP.fir.sm8.rh 
funcroi-config -roi BaleenLP.rh.fir.034.roicfg -label aparc2009-rh-034.label -analysis ya.BaleenLP.fir.sm8.rh 
funcroi-config -roi BaleenLP.rh.fir.037.roicfg -label aparc2009-rh-037.label -analysis ya.BaleenLP.fir.sm8.rh 
funcroi-config -roi BaleenLP.rh.fir.038.roicfg -label aparc2009-rh-038.label -analysis ya.BaleenLP.fir.sm8.rh 
funcroi-config -roi BaleenLP.rh.fir.044.roicfg -label aparc2009-rh-044.label -analysis ya.BaleenLP.fir.sm8.rh 
funcroi-config -roi BaleenLP.rh.fir.073.roicfg -label aparc2009-rh-073.label -analysis ya.BaleenLP.fir.sm8.rh 
funcroi-config -roi BaleenLP.rh.fir.074.roicfg -label aparc2009-rh-074.label -analysis ya.BaleenLP.fir.sm8.rh 
funcroi-config -roi BaleenLP.rh.spm.012.roicfg -label aparc2009-rh-012.label -analysis ya.BaleenLP.spm.sm8.rh 
funcroi-config -roi BaleenLP.rh.spm.025.roicfg -label aparc2009-rh-025.label -analysis ya.BaleenLP.spm.sm8.rh 
funcroi-config -roi BaleenLP.rh.spm.034.roicfg -label aparc2009-rh-034.label -analysis ya.BaleenLP.spm.sm8.rh 
funcroi-config -roi BaleenLP.rh.spm.037.roicfg -label aparc2009-rh-037.label -analysis ya.BaleenLP.spm.sm8.rh 
funcroi-config -roi BaleenLP.rh.spm.038.roicfg -label aparc2009-rh-038.label -analysis ya.BaleenLP.spm.sm8.rh 
funcroi-config -roi BaleenLP.rh.spm.044.roicfg -label aparc2009-rh-044.label -analysis ya.BaleenLP.spm.sm8.rh 
funcroi-config -roi BaleenLP.rh.spm.073.roicfg -label aparc2009-rh-073.label -analysis ya.BaleenLP.spm.sm8.rh 
funcroi-config -roi BaleenLP.rh.spm.074.roicfg -label aparc2009-rh-074.label -analysis ya.BaleenLP.spm.sm8.rh 
