funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.fir.aparc2009-lh-074.roicfg -label aparc2009-lh-074.label -analysis ya.ATLLoc.fir.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.fir.aparc2009-lh-034.roicfg -label aparc2009-lh-034.label -analysis ya.ATLLoc.fir.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.fir.aparc2009-lh-037.roicfg -label aparc2009-lh-037.label -analysis ya.ATLLoc.fir.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.fir.lh.BA45.roicfg -label lh.BA45.label -analysis ya.ATLLoc.fir.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.fir.aparc2009-lh-044.roicfg -label aparc2009-lh-044.label -analysis ya.ATLLoc.fir.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.fir.aparc2009-lh-025.roicfg -label aparc2009-lh-025.label -analysis ya.ATLLoc.fir.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.fir.lh.BA44.roicfg -label lh.BA44.label -analysis ya.ATLLoc.fir.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.fir.aparc2009-lh-073.roicfg -label aparc2009-lh-073.label -analysis ya.ATLLoc.fir.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.fir.aparc2009-lh-012.roicfg -label aparc2009-lh-012.label -analysis ya.ATLLoc.fir.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.fir.aparc2009-lh-038.roicfg -label aparc2009-lh-038.label -analysis ya.ATLLoc.fir.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.spm.aparc2009-lh-074.roicfg -label aparc2009-lh-074.label -analysis ya.ATLLoc.spm.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.spm.aparc2009-lh-034.roicfg -label aparc2009-lh-034.label -analysis ya.ATLLoc.spm.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.spm.aparc2009-lh-037.roicfg -label aparc2009-lh-037.label -analysis ya.ATLLoc.spm.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.spm.lh.BA45.roicfg -label lh.BA45.label -analysis ya.ATLLoc.spm.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.spm.aparc2009-lh-044.roicfg -label aparc2009-lh-044.label -analysis ya.ATLLoc.spm.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.spm.aparc2009-lh-025.roicfg -label aparc2009-lh-025.label -analysis ya.ATLLoc.spm.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.spm.lh.BA44.roicfg -label lh.BA44.label -analysis ya.ATLLoc.spm.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.spm.aparc2009-lh-073.roicfg -label aparc2009-lh-073.label -analysis ya.ATLLoc.spm.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.spm.aparc2009-lh-012.roicfg -label aparc2009-lh-012.label -analysis ya.ATLLoc.spm.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.lh.spm.aparc2009-lh-038.roicfg -label aparc2009-lh-038.label -analysis ya.ATLLoc.spm.sm8.lh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.fir.aparc2009-rh-074.roicfg -label aparc2009-rh-074.label -analysis ya.ATLLoc.fir.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.fir.aparc2009-rh-034.roicfg -label aparc2009-rh-034.label -analysis ya.ATLLoc.fir.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.fir.aparc2009-rh-037.roicfg -label aparc2009-rh-037.label -analysis ya.ATLLoc.fir.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.fir.rh.BA45.roicfg -label rh.BA45.label -analysis ya.ATLLoc.fir.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.fir.aparc2009-rh-044.roicfg -label aparc2009-rh-044.label -analysis ya.ATLLoc.fir.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.fir.aparc2009-rh-025.roicfg -label aparc2009-rh-025.label -analysis ya.ATLLoc.fir.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.fir.rh.BA44.roicfg -label rh.BA44.label -analysis ya.ATLLoc.fir.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.fir.aparc2009-rh-073.roicfg -label aparc2009-rh-073.label -analysis ya.ATLLoc.fir.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.fir.aparc2009-rh-012.roicfg -label aparc2009-rh-012.label -analysis ya.ATLLoc.fir.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.fir.aparc2009-rh-038.roicfg -label aparc2009-rh-038.label -analysis ya.ATLLoc.fir.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.spm.aparc2009-rh-074.roicfg -label aparc2009-rh-074.label -analysis ya.ATLLoc.spm.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.spm.aparc2009-rh-034.roicfg -label aparc2009-rh-034.label -analysis ya.ATLLoc.spm.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.spm.aparc2009-rh-037.roicfg -label aparc2009-rh-037.label -analysis ya.ATLLoc.spm.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.spm.rh.BA45.roicfg -label rh.BA45.label -analysis ya.ATLLoc.spm.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.spm.aparc2009-rh-044.roicfg -label aparc2009-rh-044.label -analysis ya.ATLLoc.spm.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.spm.aparc2009-rh-025.roicfg -label aparc2009-rh-025.label -analysis ya.ATLLoc.spm.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.spm.rh.BA44.roicfg -label rh.BA44.label -analysis ya.ATLLoc.spm.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.spm.aparc2009-rh-073.roicfg -label aparc2009-rh-073.label -analysis ya.ATLLoc.spm.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.spm.aparc2009-rh-012.roicfg -label aparc2009-rh-012.label -analysis ya.ATLLoc.spm.sm8.rh 
funcroi-config -roi /cluster/kuperberg/SemPrMM/MRI/functionals/roi_cfg/ATLLoc.rh.spm.aparc2009-rh-038.roicfg -label aparc2009-rh-038.label -analysis ya.ATLLoc.spm.sm8.rh 
