funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-012.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-012.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-012.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-012.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-025.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-025.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-025.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-025.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-034.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-034.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-034.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-034.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-037.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-037.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-037.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-037.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-038.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-038.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-038.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-038.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-044.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-044.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-044.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-044.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-073.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-073.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-073.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-073.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-074.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-074.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-lh-074.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-074.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.lh.BA44.cespct.Unrelated.dat -roi BaleenHP.lh.fir.lh.BA44.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.lh.BA44.cespct.Related.dat -roi BaleenHP.lh.fir.lh.BA44.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.lh.BA45.cespct.Unrelated.dat -roi BaleenHP.lh.fir.lh.BA45.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.lh.BA45.cespct.Related.dat -roi BaleenHP.lh.fir.lh.BA45.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-012.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-012.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-012.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-012.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-025.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-025.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-025.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-025.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-034.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-034.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-034.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-034.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-037.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-037.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-037.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-037.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-038.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-038.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-038.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-038.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-044.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-044.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-044.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-044.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-073.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-073.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-073.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-073.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-074.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-074.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-lh-074.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-074.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.lh.BA44.cespct.Unrelated.dat -roi BaleenHP.lh.spm.lh.BA44.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.lh.BA44.cespct.Related.dat -roi BaleenHP.lh.spm.lh.BA44.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.lh.BA45.cespct.Unrelated.dat -roi BaleenHP.lh.spm.lh.BA45.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.lh.BA45.cespct.Related.dat -roi BaleenHP.lh.spm.lh.BA45.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-012.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-012.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-012.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-012.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-025.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-025.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-025.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-025.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-034.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-034.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-034.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-034.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-037.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-037.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-037.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-037.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-038.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-038.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-038.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-038.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-044.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-044.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-044.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-044.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-073.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-073.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-073.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-073.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-074.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-074.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-rh-074.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-074.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.rh.BA44.cespct.Unrelated.dat -roi BaleenHP.rh.fir.rh.BA44.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.rh.BA44.cespct.Related.dat -roi BaleenHP.rh.fir.rh.BA44.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.rh.BA45.cespct.Unrelated.dat -roi BaleenHP.rh.fir.rh.BA45.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.rh.BA45.cespct.Related.dat -roi BaleenHP.rh.fir.rh.BA45.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-012.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-012.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-012.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-012.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-025.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-025.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-025.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-025.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-034.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-034.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-034.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-034.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-037.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-037.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-037.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-037.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-038.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-038.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-038.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-038.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-044.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-044.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-044.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-044.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-073.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-073.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-073.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-073.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-074.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-074.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-rh-074.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-074.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.rh.BA44.cespct.Unrelated.dat -roi BaleenHP.rh.spm.rh.BA44.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.rh.BA44.cespct.Related.dat -roi BaleenHP.rh.spm.rh.BA44.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.rh.BA45.cespct.Unrelated.dat -roi BaleenHP.rh.spm.rh.BA45.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.rh.BA45.cespct.Related.dat -roi BaleenHP.rh.spm.rh.BA45.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-012.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-012.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-012.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-012.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-025.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-025.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-025.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-025.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-034.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-034.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-034.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-034.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-037.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-037.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-037.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-037.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-038.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-038.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-038.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-038.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-044.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-044.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-044.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-044.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-073.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-073.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-073.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-073.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-074.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-074.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-lh-074.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-074.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.lh.BA44.cespct.Unrelated.dat -roi BaleenLP.lh.fir.lh.BA44.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.lh.BA44.cespct.Related.dat -roi BaleenLP.lh.fir.lh.BA44.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.lh.BA45.cespct.Unrelated.dat -roi BaleenLP.lh.fir.lh.BA45.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.lh.BA45.cespct.Related.dat -roi BaleenLP.lh.fir.lh.BA45.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-012.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-012.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-012.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-012.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-025.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-025.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-025.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-025.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-034.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-034.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-034.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-034.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-037.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-037.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-037.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-037.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-038.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-038.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-038.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-038.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-044.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-044.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-044.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-044.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-073.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-073.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-073.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-073.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-074.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-074.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-lh-074.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-074.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.lh.BA44.cespct.Unrelated.dat -roi BaleenLP.lh.spm.lh.BA44.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.lh.BA44.cespct.Related.dat -roi BaleenLP.lh.spm.lh.BA44.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.lh.BA45.cespct.Unrelated.dat -roi BaleenLP.lh.spm.lh.BA45.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.lh.BA45.cespct.Related.dat -roi BaleenLP.lh.spm.lh.BA45.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-012.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-012.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-012.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-012.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-025.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-025.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-025.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-025.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-034.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-034.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-034.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-034.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-037.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-037.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-037.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-037.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-038.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-038.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-038.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-038.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-044.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-044.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-044.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-044.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-073.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-073.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-073.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-073.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-074.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-074.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-rh-074.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-074.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.rh.BA44.cespct.Unrelated.dat -roi BaleenLP.rh.fir.rh.BA44.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.rh.BA44.cespct.Related.dat -roi BaleenLP.rh.fir.rh.BA44.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.rh.BA45.cespct.Unrelated.dat -roi BaleenLP.rh.fir.rh.BA45.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.rh.BA45.cespct.Related.dat -roi BaleenLP.rh.fir.rh.BA45.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-012.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-012.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-012.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-012.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-025.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-025.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-025.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-025.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-034.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-034.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-034.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-034.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-037.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-037.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-037.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-037.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-038.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-038.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-038.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-038.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-044.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-044.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-044.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-044.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-073.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-073.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-073.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-073.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-074.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-074.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-rh-074.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-074.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.rh.BA44.cespct.Unrelated.dat -roi BaleenLP.rh.spm.rh.BA44.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.rh.BA44.cespct.Related.dat -roi BaleenLP.rh.spm.rh.BA44.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.rh.BA45.cespct.Unrelated.dat -roi BaleenLP.rh.spm.rh.BA45.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.rh.BA45.cespct.Related.dat -roi BaleenLP.rh.spm.rh.BA45.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Related -map cespct -frame 0 & 
 wait
