funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.S_temporal_sup.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.S_temporal_sup.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.S_temporal_sup.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.S_temporal_sup.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.S_temporal_sup.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.S_temporal_sup.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_temp_sup-Lateral.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_temp_sup-Lateral.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_temp_sup-Lateral.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_temp_sup-Lateral.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_temp_sup-Lateral.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_temp_sup-Lateral.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_temporal_inf.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_temporal_inf.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_temporal_inf.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_temporal_inf.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 wait
funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_temporal_inf.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_temporal_inf.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.Pole_temporal.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.Pole_temporal.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.Pole_temporal.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.Pole_temporal.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.Pole_temporal.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.Pole_temporal.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_pariet_inf-Angular.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_pariet_inf-Angular.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_pariet_inf-Angular.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_pariet_inf-Angular.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_pariet_inf-Angular.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_pariet_inf-Angular.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.S_temporal_inf.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.S_temporal_inf.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 wait
funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.S_temporal_inf.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.S_temporal_inf.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.S_temporal_inf.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.S_temporal_inf.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_front_inf-Triangul.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_front_inf-Triangul.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_front_inf-Triangul.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_front_inf-Triangul.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_front_inf-Triangul.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_front_inf-Triangul.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_front_inf-Orbital.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_front_inf-Orbital.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_front_inf-Orbital.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_front_inf-Orbital.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_front_inf-Orbital.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_front_inf-Orbital.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 wait
funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_front_inf-Opercular.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_front_inf-Opercular.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_front_inf-Opercular.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_front_inf-Opercular.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_front_inf-Opercular.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_front_inf-Opercular.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_temporal_middle.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_temporal_middle.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_temporal_middle.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_temporal_middle.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.lh.shrf.G_temporal_middle.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.lh.shrf.G_temporal_middle.roicfg -analysis MaskedMM.shrf.sm8.lh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.S_temporal_sup.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.S_temporal_sup.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.S_temporal_sup.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.S_temporal_sup.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 wait
funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.S_temporal_sup.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.S_temporal_sup.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_temp_sup-Lateral.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_temp_sup-Lateral.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_temp_sup-Lateral.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_temp_sup-Lateral.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_temp_sup-Lateral.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_temp_sup-Lateral.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_temporal_inf.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_temporal_inf.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_temporal_inf.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_temporal_inf.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_temporal_inf.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_temporal_inf.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.Pole_temporal.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.Pole_temporal.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 wait
funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.Pole_temporal.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.Pole_temporal.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.Pole_temporal.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.Pole_temporal.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_pariet_inf-Angular.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_pariet_inf-Angular.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_pariet_inf-Angular.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_pariet_inf-Angular.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_pariet_inf-Angular.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_pariet_inf-Angular.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.S_temporal_inf.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.S_temporal_inf.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.S_temporal_inf.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.S_temporal_inf.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.S_temporal_inf.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.S_temporal_inf.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 wait
funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_front_inf-Triangul.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_front_inf-Triangul.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_front_inf-Triangul.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_front_inf-Triangul.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_front_inf-Triangul.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_front_inf-Triangul.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_front_inf-Orbital.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_front_inf-Orbital.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_front_inf-Orbital.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_front_inf-Orbital.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_front_inf-Orbital.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_front_inf-Orbital.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_front_inf-Opercular.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_front_inf-Opercular.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_front_inf-Opercular.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_front_inf-Opercular.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 wait
funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_front_inf-Opercular.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_front_inf-Opercular.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_temporal_middle.cespct.Unrelated.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_temporal_middle.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_temporal_middle.cespct.Indirect.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_temporal_middle.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Indirect -map cespct -frame 0 & 
 funcroi-table-sess -o /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/dat/sc.MaskedMM.rh.shrf.G_temporal_middle.cespct.Direct.dat -roi /cluster/kuperberg/SemPrMM/MRI/results/roi_fsfast/roi_cfg/MaskedMM.rh.shrf.G_temporal_middle.roicfg -analysis MaskedMM.shrf.sm8.rh -sf sc.group-analysis/sc.MaskedMM.sessid -d /cluster/kuperberg/SemPrMM/MRI/functionals/ -contrast Direct -map cespct -frame 0 & 
 