funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-012.label.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-012.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-012.label.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-012.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-025.label.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-025.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-025.label.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-025.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-034.label.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-034.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-034.label.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-034.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-037.label.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-037.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-037.label.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-037.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-038.label.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-038.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-038.label.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-038.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-044.label.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-044.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-044.label.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-044.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-073.label.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-073.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-073.label.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-073.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-074.label.cespct.Unrelated.dat -roi BaleenHP.lh.fir.aparc2009-lh-074.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.aparc2009-%s-074.label.cespct.Related.dat -roi BaleenHP.lh.fir.aparc2009-lh-074.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.%s.BA44.label.cespct.Unrelated.dat -roi BaleenHP.lh.fir.lh.BA44.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.%s.BA44.label.cespct.Related.dat -roi BaleenHP.lh.fir.lh.BA44.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.%s.BA45.label.cespct.Unrelated.dat -roi BaleenHP.lh.fir.lh.BA45.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.fir.%s.BA45.label.cespct.Related.dat -roi BaleenHP.lh.fir.lh.BA45.label.roicfg -analysis ya.BaleenHP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-012.label.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-012.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-012.label.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-012.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-025.label.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-025.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-025.label.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-025.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-034.label.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-034.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-034.label.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-034.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-037.label.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-037.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-037.label.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-037.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-038.label.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-038.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-038.label.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-038.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-044.label.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-044.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-044.label.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-044.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-073.label.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-073.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-073.label.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-073.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-074.label.cespct.Unrelated.dat -roi BaleenHP.lh.spm.aparc2009-lh-074.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.aparc2009-%s-074.label.cespct.Related.dat -roi BaleenHP.lh.spm.aparc2009-lh-074.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.%s.BA44.label.cespct.Unrelated.dat -roi BaleenHP.lh.spm.lh.BA44.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.%s.BA44.label.cespct.Related.dat -roi BaleenHP.lh.spm.lh.BA44.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.%s.BA45.label.cespct.Unrelated.dat -roi BaleenHP.lh.spm.lh.BA45.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.lh.spm.%s.BA45.label.cespct.Related.dat -roi BaleenHP.lh.spm.lh.BA45.label.roicfg -analysis ya.BaleenHP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-012.label.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-012.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-012.label.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-012.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-025.label.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-025.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-025.label.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-025.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-034.label.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-034.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-034.label.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-034.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-037.label.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-037.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-037.label.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-037.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-038.label.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-038.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-038.label.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-038.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-044.label.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-044.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-044.label.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-044.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-073.label.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-073.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-073.label.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-073.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-074.label.cespct.Unrelated.dat -roi BaleenHP.rh.fir.aparc2009-rh-074.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.aparc2009-%s-074.label.cespct.Related.dat -roi BaleenHP.rh.fir.aparc2009-rh-074.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.%s.BA44.label.cespct.Unrelated.dat -roi BaleenHP.rh.fir.rh.BA44.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.%s.BA44.label.cespct.Related.dat -roi BaleenHP.rh.fir.rh.BA44.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.%s.BA45.label.cespct.Unrelated.dat -roi BaleenHP.rh.fir.rh.BA45.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.fir.%s.BA45.label.cespct.Related.dat -roi BaleenHP.rh.fir.rh.BA45.label.roicfg -analysis ya.BaleenHP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-012.label.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-012.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-012.label.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-012.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-025.label.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-025.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-025.label.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-025.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-034.label.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-034.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-034.label.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-034.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-037.label.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-037.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-037.label.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-037.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-038.label.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-038.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-038.label.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-038.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-044.label.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-044.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-044.label.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-044.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-073.label.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-073.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-073.label.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-073.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-074.label.cespct.Unrelated.dat -roi BaleenHP.rh.spm.aparc2009-rh-074.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.aparc2009-%s-074.label.cespct.Related.dat -roi BaleenHP.rh.spm.aparc2009-rh-074.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.%s.BA44.label.cespct.Unrelated.dat -roi BaleenHP.rh.spm.rh.BA44.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.%s.BA44.label.cespct.Related.dat -roi BaleenHP.rh.spm.rh.BA44.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.%s.BA45.label.cespct.Unrelated.dat -roi BaleenHP.rh.spm.rh.BA45.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenHP.rh.spm.%s.BA45.label.cespct.Related.dat -roi BaleenHP.rh.spm.rh.BA45.label.roicfg -analysis ya.BaleenHP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-012.label.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-012.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-012.label.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-012.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-025.label.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-025.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-025.label.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-025.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-034.label.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-034.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-034.label.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-034.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-037.label.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-037.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-037.label.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-037.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-038.label.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-038.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-038.label.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-038.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-044.label.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-044.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-044.label.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-044.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-073.label.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-073.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-073.label.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-073.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-074.label.cespct.Unrelated.dat -roi BaleenLP.lh.fir.aparc2009-lh-074.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.aparc2009-%s-074.label.cespct.Related.dat -roi BaleenLP.lh.fir.aparc2009-lh-074.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.%s.BA44.label.cespct.Unrelated.dat -roi BaleenLP.lh.fir.lh.BA44.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.%s.BA44.label.cespct.Related.dat -roi BaleenLP.lh.fir.lh.BA44.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.%s.BA45.label.cespct.Unrelated.dat -roi BaleenLP.lh.fir.lh.BA45.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.fir.%s.BA45.label.cespct.Related.dat -roi BaleenLP.lh.fir.lh.BA45.label.roicfg -analysis ya.BaleenLP.fir.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-012.label.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-012.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-012.label.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-012.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-025.label.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-025.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-025.label.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-025.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-034.label.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-034.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-034.label.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-034.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-037.label.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-037.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-037.label.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-037.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-038.label.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-038.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-038.label.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-038.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-044.label.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-044.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-044.label.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-044.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-073.label.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-073.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-073.label.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-073.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-074.label.cespct.Unrelated.dat -roi BaleenLP.lh.spm.aparc2009-lh-074.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.aparc2009-%s-074.label.cespct.Related.dat -roi BaleenLP.lh.spm.aparc2009-lh-074.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.%s.BA44.label.cespct.Unrelated.dat -roi BaleenLP.lh.spm.lh.BA44.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.%s.BA44.label.cespct.Related.dat -roi BaleenLP.lh.spm.lh.BA44.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.%s.BA45.label.cespct.Unrelated.dat -roi BaleenLP.lh.spm.lh.BA45.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.lh.spm.%s.BA45.label.cespct.Related.dat -roi BaleenLP.lh.spm.lh.BA45.label.roicfg -analysis ya.BaleenLP.spm.sm8.lh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-012.label.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-012.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-012.label.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-012.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-025.label.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-025.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-025.label.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-025.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-034.label.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-034.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-034.label.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-034.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-037.label.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-037.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-037.label.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-037.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-038.label.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-038.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-038.label.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-038.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-044.label.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-044.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-044.label.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-044.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-073.label.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-073.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-073.label.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-073.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-074.label.cespct.Unrelated.dat -roi BaleenLP.rh.fir.aparc2009-rh-074.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.aparc2009-%s-074.label.cespct.Related.dat -roi BaleenLP.rh.fir.aparc2009-rh-074.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.%s.BA44.label.cespct.Unrelated.dat -roi BaleenLP.rh.fir.rh.BA44.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.%s.BA44.label.cespct.Related.dat -roi BaleenLP.rh.fir.rh.BA44.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.%s.BA45.label.cespct.Unrelated.dat -roi BaleenLP.rh.fir.rh.BA45.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.fir.%s.BA45.label.cespct.Related.dat -roi BaleenLP.rh.fir.rh.BA45.label.roicfg -analysis ya.BaleenLP.fir.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 6 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-012.label.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-012.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-012.label.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-012.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-025.label.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-025.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-025.label.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-025.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-034.label.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-034.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-034.label.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-034.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-037.label.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-037.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-037.label.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-037.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-038.label.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-038.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-038.label.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-038.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-044.label.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-044.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-044.label.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-044.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 wait
funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-073.label.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-073.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-073.label.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-073.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-074.label.cespct.Unrelated.dat -roi BaleenLP.rh.spm.aparc2009-rh-074.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.aparc2009-%s-074.label.cespct.Related.dat -roi BaleenLP.rh.spm.aparc2009-rh-074.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.%s.BA44.label.cespct.Unrelated.dat -roi BaleenLP.rh.spm.rh.BA44.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.%s.BA44.label.cespct.Related.dat -roi BaleenLP.rh.spm.rh.BA44.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.%s.BA45.label.cespct.Unrelated.dat -roi BaleenLP.rh.spm.rh.BA45.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Unrelated -map cespct -frame 0 & 
 funcroi-table-sess -o roi_summary/BaleenLP.rh.spm.%s.BA45.label.cespct.Related.dat -roi BaleenLP.rh.spm.rh.BA45.label.roicfg -analysis ya.BaleenLP.spm.sm8.rh -sf ya.BaleenHP.sessid -d . -contrast Related -map cespct -frame 0 & 
 wait
